### ISSUE TITLE
canvas url

### ISSUE THREAD

**Issue by dino-at-thegovlab** [GovLab/academy-canvas#1]
move:

http://govlab.github.io/academy-canvas/

to:

canvas.govlabacademy.org

Q for @sahuguet : if we move, what will happen with the existing urls of the canvases people already made?

**Comment by claudioccm** [comment]
nothing will happen to the URLs. Both will still work. It's a basic redirect. 

@sahuguet, I still don't have access to the domains, so I'd need your help on this.
