### ISSUE TITLE
Description Fields

### ISSUE THREAD

**Issue by claudioccm** [GovLab/academy-canvas#13]
Description fields for Author, One Liner and Location. These fields are specific for each canvas.

**Comment by sahuguet** [comment]
Hey, can you add me as a admin for the Firebase DB?
I need to delete a few things.

Welcome back, my friend.

On Fri, May 1, 2015 at 3:26 PM, Claudio Mendonca notifications@github.com
wrote:

> Create a "Description Field", to go below the title and above the
> "Understand" title, so users can add extra information about their canvas.
> Things like "Authors, One Liner and Meta Data.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GovLab/academy-canvas/issues/13.

## 

Arnaud Sahuguet
– Chief Technology Officer
