### ISSUE TITLE
privacy settings - lock/unlock button

### ISSUE THREAD

**Issue by dino-at-thegovlab** [GovLab/academy-canvas#2]
For now, people can choose to create a password. 

Add option for people to "unlock" it so that anyone can see it. 

Add option for people to lock it again.

**Comment by talos** [comment]
Do you mean a similar interface as to what's available on cell phones?

If so, I would be against doing this.  The standard for inputting computer passwords is that they cannot be made visible.

**Comment by dino-at-thegovlab** [comment]
Password is for people who don't want their canvas visible. But maybe, after working on it, they want it to be visible again, so that's what I mean with "unlock" option. 

Also, people have already submitted their canvas, should have the option of making it private, so by having a "lock" button, would be useful for the, to add a password for someone to see it.

**Comment by talos** [comment]
Got it, you were talking about password for the canvas.  Yes, this is doable then.

**Comment by dino-at-thegovlab** [comment]
haha yes, sorry. 

my message was kind of cryptic
