### ISSUE TITLE
add "one-liner" square

### ISSUE THREAD

**Issue by dino-at-thegovlab** [GovLab/academy-canvas#4]
Below the title of the project, can we add a "one-liner" square?

Text:
One line description of the project... (purple format)
What is your high-concept pitch? How would you summarize your vision into a single phrase or sentence? (grey format)

**Comment by claudioccm** [comment]
I agree that we might need a description field for each canvas. I saw that you added 3 similar requests here. "Authors", "One Liner" and "MetaData". Maybe it is wiser to just add one "Description" field, that supports something around 400 characters, and people will be able to fill in all these extra information. 
What do you think?
